apiVersion: v1
kind: Secret
metadata:
  name: assetflow-secrets
  namespace: assetflow
type: Opaque
stringData:
  MONGO_USERNAME: "assetflow"
  MONGO_PASSWORD: "assetflow123"
  REDIS_PASSWORD: "redis123"
  JWT_SECRET_KEY: "super-secret-jwt-key-change-in-production-min-32-chars"
  BANK_MONGO_URI: "mongodb://assetflow:assetflow123@mongodb:27017/bank_simulator?authSource=admin"
  ASSETFLOW_MONGO_URI: "mongodb://assetflow:assetflow123@mongodb:27017/assetflow?authSource=admin"
